version: "3"

services:
  PROVIDER_ANALYTICS_POSTGRES:
    image: postgres:latest
    container_name: PROVIDER_ANALYTICS_POSTGRES
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: this0is0a0secret0password
      POSTGRES_DB: verceldb
