import type { AppRouterOutput } from "@chair-flight/trpc/server";

export const mockData: AppRouterOutput["containers"]["questions"]["getQuestionEditor"] =
  {
    questionTemplate: {
      id: "Q000YBA1ON",
      learningObjectives: ["010.01"],
      explanation: "",
      srcLocation: "libs/content/question-bank-atpl/questions/010/010.01.json",
      variants: {
        dsLWKxr9: {
          type: "simple",
          id: "dsLWKxr9",
          question:
            "Annex 14 to the convention on international civil aviation contains SARPS for:",
          options: [
            { id: "AIXXXDXGUH", text: "aerodromes.", correct: true, why: "" },
            { id: "A18NL7DOHU", text: "security.", correct: false, why: "" },
            {
              id: "AC0EHU7TT6",
              text: "facilitation.",
              correct: false,
              why: "",
            },
            {
              id: "A55C2LXDYK",
              text: "none of the above.",
              correct: false,
              why: "",
            },
          ],
          annexes: [],
          externalIds: ["AVEXAM-67778", "ATPLGS-622143", "AVEXAM-67778"],
          explanation: "",
        },
      },
    },
  };

export const mockSearchData: AppRouterOutput["common"]["search"]["searchLearningObjectives"] =
  {
    items: [
      {
        id: "010.11.01.01",
        href: "/modules/atpl/learning-objectives/010.11.01.01",
        parentId: "010.11.01",
        courses: [
          { id: "ATPL_A", text: "ATPL(A)" },
          { id: "CPL_A", text: "CPL(A)" },
          { id: "ATPL_H_IR", text: "ATPL(H) IR" },
          { id: "ATPL_H_VFR", text: "ATPL(H) VFR" },
          { id: "CPL_H", text: "CPL(H)" },
        ],
        text: "Essential Sar definitions - Icao Annex 12",
        source: "ICAO Annex 12",
        questionBank: "atpl",
        subject: "010",
        numberOfQuestions: 3,
      },
      {
        id: "040.02.01.02.25",
        href: "/modules/atpl/learning-objectives/040.02.01.02.25",
        parentId: "040.02.01.02",
        courses: [
          { id: "ATPL_A", text: "ATPL(A)" },
          { id: "CPL_A", text: "CPL(A)" },
          { id: "ATPL_H_IR", text: "ATPL(H) IR" },
          { id: "ATPL_H_VFR", text: "ATPL(H) VFR" },
          { id: "CPL_H", text: "CPL(H)" },
          { id: "IR", text: "IR" },
        ],
        text: "State that healthy people are able to compensate for altitudes up to approximately 10 000-12 000 ft.",
        source: "",
        questionBank: "atpl",
        subject: "040",
        numberOfQuestions: 2,
      },
      {
        id: "040.02.01.02.26",
        href: "/modules/atpl/learning-objectives/040.02.01.02.26",
        parentId: "040.02.01.02",
        courses: [
          { id: "ATPL_A", text: "ATPL(A)" },
          { id: "CPL_A", text: "CPL(A)" },
          { id: "ATPL_H_IR", text: "ATPL(H) IR" },
          { id: "ATPL_H_VFR", text: "ATPL(H) VFR" },
          { id: "CPL_H", text: "CPL(H)" },
          { id: "IR", text: "IR" },
        ],
        text: "Name the three physiological thresholds and allocate the corresponding altitudes for each of them:\n-  reaction threshold (7 000 ft);\n-  disturbance threshold (10-12 000 ft);\n-  and critical threshold (22 000 ft).",
        source: "",
        questionBank: "atpl",
        subject: "040",
        numberOfQuestions: 4,
      },
      {
        id: "010.07.02.12.12",
        href: "/modules/atpl/learning-objectives/010.07.02.12.12",
        parentId: "010.07.02.12",
        courses: [
          { id: "ATPL_A", text: "ATPL(A)" },
          { id: "ATPL_H_IR", text: "ATPL(H) IR" },
          { id: "IR", text: "IR" },
          { id: "CBIR_A", text: "CBIR(A)" },
        ],
        text: "Describe track separation between aircraft using the same navigation aid or method.",
        source:
          "ICAO Doc 4444, Chapter 5, 5.4.1.2 Lateral separation criteria and minima, 5.4.1.2.1.2",
        questionBank: "atpl",
        subject: "010",
        numberOfQuestions: 8,
      },
      {
        id: "022.12.10.01.12",
        href: "/modules/atpl/learning-objectives/022.12.10.01.12",
        parentId: "022.12.10.01",
        courses: [
          { id: "ATPL_A", text: "ATPL(A)" },
          { id: "CPL_A", text: "CPL(A)" },
          { id: "ATPL_H_IR", text: "ATPL(H) IR" },
          { id: "ATPL_H_VFR", text: "ATPL(H) VFR" },
          { id: "CPL_H", text: "CPL(H)" },
          { id: "IR", text: "IR" },
        ],
        text: "State the typical standard detection range for Tcas Ii:\n-  35–40 Nm horizontally;\n-  approximately 2 000 ft above and below (any setting);\n-  extension to approximately 10 000 ft above (Abv selected) or approximately 10 000 ft below (Blw selected).",
        source: "",
        questionBank: "atpl",
        subject: "022",
        numberOfQuestions: 4,
      },
      {
        id: "071.02.12.03.12",
        href: "/modules/atpl/learning-objectives/071.02.12.03.12",
        parentId: "071.02.12.03",
        courses: [
          { id: "ATPL_A", text: "ATPL(A)" },
          { id: "CPL_A", text: "CPL(A)" },
          { id: "ATPL_H_IR", text: "ATPL(H) IR" },
          { id: "ATPL_H_VFR", text: "ATPL(H) VFR" },
          { id: "CPL_H", text: "CPL(H)" },
        ],
        text: "Explain the need for an inspection prior to loading dangerous goods on an aircraft. ",
        source:
          "CAT.GEN.MPA.200 ‘Transport of dangerous goods’; \r\nAMC1 SPA.DG.110(b) ‘Dangerous goods information and documentation’",
        questionBank: "atpl",
        subject: "071",
        numberOfQuestions: 9,
      },
      {
        id: "010.12",
        href: "/modules/atpl/learning-objectives/010.12",
        parentId: "010",
        courses: [
          { id: "ATPL_A", text: "ATPL(A)" },
          { id: "CPL_A", text: "CPL(A)" },
          { id: "ATPL_H_IR", text: "ATPL(H) IR" },
          { id: "ATPL_H_VFR", text: "ATPL(H) VFR" },
          { id: "CPL_H", text: "CPL(H)" },
        ],
        text: "Security - Safeguarding International Civil Aviation against Acts of Unlawful Interference (Icao Annex 17) ",
        source: "ICAO Annex 17",
        questionBank: "atpl",
        subject: "010",
        numberOfQuestions: 70,
      },
      {
        id: "021.12",
        href: "/modules/atpl/learning-objectives/021.12",
        parentId: "021",
        courses: [
          { id: "ATPL_H_IR", text: "ATPL(H) IR" },
          { id: "ATPL_H_VFR", text: "ATPL(H) VFR" },
          { id: "CPL_H", text: "CPL(H)" },
          { id: "ATPL_A", text: "ATPL(A)" },
          { id: "CPL_A", text: "CPL(A)" },
        ],
        text: "Protection And Detection Systems",
        source: "",
        questionBank: "atpl",
        subject: "021",
        numberOfQuestions: 58,
      },
      {
        id: "022.12",
        href: "/modules/atpl/learning-objectives/022.12",
        parentId: "022",
        courses: [
          { id: "ATPL_H_IR", text: "ATPL(H) IR" },
          { id: "ATPL_H_VFR", text: "ATPL(H) VFR" },
          { id: "CPL_H", text: "CPL(H)" },
          { id: "ATPL_A", text: "ATPL(A)" },
          { id: "CPL_A", text: "CPL(A)" },
          { id: "IR", text: "IR" },
        ],
        text: "Alerting Systems, Proximity Systems",
        source: "",
        questionBank: "atpl",
        subject: "022",
        numberOfQuestions: 344,
      },
      {
        id: "010.12.01",
        href: "/modules/atpl/learning-objectives/010.12.01",
        parentId: "010.12",
        courses: [
          { id: "ATPL_A", text: "ATPL(A)" },
          { id: "CPL_A", text: "CPL(A)" },
          { id: "ATPL_H_IR", text: "ATPL(H) IR" },
          { id: "ATPL_H_VFR", text: "ATPL(H) VFR" },
          { id: "CPL_H", text: "CPL(H)" },
        ],
        text: "Definitions of Icao Annex 17",
        source: "",
        questionBank: "atpl",
        subject: "010",
        numberOfQuestions: 4,
      },
    ],
    totalResults: 245,
    nextCursor: 10,
  };
