import type { AppRouterOutput } from "@chair-flight/trpc/server";

export const mockData: AppRouterOutput["containers"]["learningObjectives"]["getLearningObjectiveOverview"] =
  {
    learningObjective: {
      id: "010.01.01",
      parentId: "010.01",
      courses: ["ATPL_A", "CPL_A", "ATPL_H_IR", "ATPL_H_VFR", "CPL_H"],
      text: {
        mdContent:
          "The Convention on International Civil Aviation (Chicago) - Icao Doc 7300/9 - Convention on the High Seas (Geneva, 29 April 1958)",
      },
      learningObjectives: ["010.01.01.01", "010.01.01.02", "010.01.01.03"],
      questionBank: "atpl",
      source: { mdContent: "" },
      questions: [],
      nestedQuestions: [
        "QREHZNEE",
        "QOAKYFTL",
        "QEIKKBDI",
        "QQTPLVIH",
        "QBQCJRZL",
        "QVMCBJGO",
        "QJVHXHIE",
        "QFCBSEHY",
        "QNTLSOYN",
        "QHCSYHEB",
        "QYTTDCYK",
        "QIRZMTWQ",
        "QRUQRUBJ",
        "QREDYPSP",
        "QUUYQKXD",
        "QTDECDKB",
        "QXOGDMKK",
        "QMVOWMMZ",
        "QAYEUPYM",
        "QFPVLXKV",
        "QLNSDCYV",
        "QQHHTIZS",
        "QGMOJSZG",
        "QIJHDBNC",
        "QHNYHLYL",
        "QGRKGBDB",
        "QIQEMVYN",
        "QWKXJWYX",
        "QRATRLXE",
        "QEILNZEZ",
        "QIKXIGHT",
        "QXZGICZT",
        "QYNJTGWT",
        "QNHVRHIW",
        "QIGVAGLA",
        "QDNTFLZC",
        "QLCWDNUJ",
        "QOQYLGDD",
        "QFKUBGPM",
        "QWHUIIHN",
        "QDUFZWTS",
        "QTICBDLR",
        "QABCXYSQ",
        "QPDFDFGG",
        "QNMRSLKA",
        "QMYBNRTC",
        "QAPDQNHY",
        "QOERYNGB",
        "QRTKGXXR",
        "QJBVIIHM",
        "QGTXZGVX",
        "QZNQLBUV",
        "QUUAWYGJ",
        "QDDLHMKS",
        "QDQVJEAR",
        "QDGSDYLM",
        "QYONPRXR",
        "QIGYGMZV",
        "QLLJPOQX",
        "QFEBSDBQ",
        "QKZSSAOY",
        "QVLDKCEL",
        "QVEGBXLW",
        "QPXDMCUQ",
        "QPKXRQYX",
        "QCLGEIWW",
        "QDHXWVTP",
        "QQDZSCPY",
        "QPZVDFIA",
        "QZVJKUBG",
        "QVGQKQHK",
        "QKSZDWJQ",
        "QQQQTLRB",
        "QVQLIOPH",
        "QRJBQSTQ",
        "QZMZXOYK",
        "QYVPVUYE",
        "QIVJEBEY",
        "QDYNXEQH",
        "QYRPDJDS",
        "QCTHOOGS",
        "QCHNZDTJ",
        "QVSVVJUK",
        "QLYGDEUP",
        "QQPGJDGL",
        "QTNGVBFL",
        "QKCVQSWH",
        "QEMGXGGG",
        "QBDBVZJN",
        "QZHVKGCN",
        "QAXCAHBW",
        "QWCLWGFH",
        "QDFBOVPN",
        "QHMWBCYB",
        "QEGZNNKW",
        "QYOGZJOT",
        "QOMXIUVQ",
        "QAORDWHO",
        "QZMRLCWT",
        "QKUYKZOX",
        "QYZVIIIC",
        "QTDRCKEN",
        "QUBVEWSD",
        "QUFCNRYT",
        "QIJTZTYB",
        "QJHEAKMK",
      ],
    },
    courses: [
      { id: "ATPL_A", text: "ATPL(A)" },
      { id: "CPL_A", text: "CPL(A)" },
      { id: "ATPL_H_IR", text: "ATPL(H) IR" },
      { id: "ATPL_H_VFR", text: "ATPL(H) VFR" },
      { id: "CPL_H", text: "CPL(H)" },
      { id: "IR", text: "IR" },
      { id: "CBIR_A", text: "CBIR(A)" },
    ],
  };
