import { format } from "prettier/standalone";
import { getRandomId } from "@chair-flight/core/app";
import { getOctokit } from "../config/oktokit";
import type { QuestionTemplate } from "@chair-flight/base/types";

export const createNewQuestionPr = async (question: QuestionTemplate) => {
  const prId = getRandomId();
  const { octokit, owner, repo } = getOctokit();
  const baseBranch = "main";
  const newBranch = `feat-question-${question.id}-${prId}`;
  const title = `feat(question): update question ${question.id}`;
  const srcLocation = question.srcLocation.replace(/^\//, "");

  const baseBranchRef = await octokit.rest.git.getRef({
    owner,
    repo,
    ref: `heads/${baseBranch}`,
  });

  const getContentResponse = await octokit.rest.repos.getContent({
    owner,
    repo,
    path: srcLocation,
    ref: baseBranchRef.data.object.sha,
    mediaType: {
      format: "raw",
    },
  });

  if (!("content" in getContentResponse.data)) {
    throw new Error("No content found in file");
  }

  const oldQuestions = JSON.parse(
    getContentResponse.data.content,
  ) as QuestionTemplate[];

  const questionWithoutSource = { ...question, srcLocation: undefined };

  const newQuestions = oldQuestions.map((q) =>
    q.id === question.id ? questionWithoutSource : q,
  );

  const newFile = await format(JSON.stringify(newQuestions, null, 2), {
    parser: "json",
  });

  const newBranchRef = await octokit.rest.git.createRef({
    owner,
    repo,
    ref: `refs/heads/${newBranch}`,
    sha: baseBranchRef.data.object.sha,
  });

  const currentCommit = await octokit.rest.git.getCommit({
    owner,
    repo,
    commit_sha: newBranchRef.data.object.sha,
  });

  const newTree = await octokit.rest.git.createTree({
    owner,
    repo,
    tree: [
      {
        path: srcLocation,
        mode: "100644",
        type: "blob",
        content: newFile,
      },
    ],
    base_tree: currentCommit.data.tree.sha,
  });

  const newCommit = await octokit.rest.git.createCommit({
    owner,
    repo,
    author: {
      name: "Chair Flight Bot",
      email: "bot@chair-flight.com",
    },
    message: title,
    tree: newTree.data.sha,
    parents: [currentCommit.data.sha],
  });

  await octokit.rest.git.updateRef({
    owner,
    repo,
    ref: `heads/${newBranch}`,
    sha: newCommit.data.sha,
  });

  const response = await octokit.rest.pulls.create({
    owner,
    repo,
    head: newBranch,
    base: baseBranch,
    title: title,
    author: {
      name: "Chair Flight Bot",
      email: "bot@chair-flight.com",
    },
    body: "Automatic PR generated by Chair Flight",
  });

  return { url: response.data.html_url };
};
