export const QUESTION = "QB-READ-ONLY-QUESTION-";
export const LEARNING_OBJECTIVE = "QB-READ-ONLY-LEARNING-OBJECTIVE-";
export const SUBJECTS = "QB-READ-ONLY-SUBJECTS";
export const FLASH_CARDS = "QB-READ-ONLY-FLASH-CARDS";
