name: Code Check

on: 
  pull_request:
    branches:
      - main

jobs:
  code-check:
   runs-on: ubuntu-latest
   steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false 
          fetch-depth: 2

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Check if paths contain 'libs/content/**.json'
        id: check_paths
        run: | 
          diff_output=$(git show --name-only HEAD --pretty="" | grep 'libs/content/.*\.json')
          echo "Diff output: $diff_output"
          echo "changed=$diff_output" >> $GITHUB_ENV

      - name: Arrange Question banks
        if: steps.check_paths.outputs.changed
        run: pnpm arrange

      - name: Run Prettier
        if: steps.check_paths.outputs.changed
        run: pnpm prettier

      - name: Commit, push files, and exit job early
        if: steps.check_paths.outputs.changed
        run: |
          git config --global user.email "bot@chair-flight.com"
          git config --global user.name "chair-flight-bot"
          git commit -am 'style: arrange question banks'
          git push
          exit 78

      - name: Run Prettier Check
        run: pnpm prettier:check

      - name: Run Lint Check
        run: pnpm lint

      - name: Run Typescript Check
        run: pnpm typecheck

      - name: Run Compilation step for tests
        run: pnpm compile

      - name: Run Tests
        run: pnpm test
