name: Code Check

on: push

env:
  NEXT_PUBLIC_BASE_URL: https://www.chair-flight.com/

jobs:
  Code-Check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Generate Prisma types
        run: pnpm generate

      - name: Run Prettier
        run: pnpm prettier --check

      - name: Run Lint
        run: pnpm lint

      - name: Run Typescript
        run: pnpm typecheck

      - name: Run Compilation step
        run: pnpm compile

      - name: Run Tests
        run: pnpm test
