name: Code Check
on: push

env:
  QUESTION_BANK_PROVIDER: local
  NEXT_PUBLIC_BASE_URL: https://www.chair-flight.com/

jobs:
  checkout_and_install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

  run_checks:
    runs-on: ubuntu-latest
    needs: [checkout_and_install]

    steps:
      - name: Run Prettier
        run: pnpm prettier

      - name: Run Lint
        run: pnpm lint

      - name: Run Typescript
        run: pnpm tsc

      - name: Run Tests
        run: pnpm test
