name: Code Check

on: 
  pull_request:
    branches:
      - main

jobs:
  code-check:
   runs-on: ubuntu-latest
   steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Detect changes to question bank content
        id: changes
        uses: dorny/paths-filter@v3
        with: 
          filters: |
            content:
              - 'libs/content/**/*.json'

      - name: Arrange Question banks
        if: steps.changes.outputs.content == 'true'
        run: pnpm arrange

      - name: Run Prettier
        if: steps.changes.outputs.content == 'true'
        run: pnpm prettier

      - name: Commit, push files, and exit job early
        if: steps.changes.outputs.content == 'true'
        run: |
          git config --global user.email "bot@chair-flight.com"
          git config --global user.name "chair-flight-bot"
          git commit -am 'style: arrange question banks'
          git commit -am 'style: empty commit to prevent infinite loop' --allow-empty
          git push
          exit 78

      - name: Run Prettier Check
        run: pnpm prettier:check

      - name: Run Lint Check
        run: pnpm lint

      - name: Run Typescript Check
        run: pnpm typecheck

      - name: Run Compilation step for tests
        run: pnpm compile

      - name: Run Tests
        run: pnpm test
